### ISSUE TITLE
MapDirs looks broke

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#1086]
I think it broke w/this commit -> https://github.com/nanovms/ops/pull/1051

```➜  test ops run -c config.json test
 100% |████████████████████████████████████████|  [0s:0s]
panic: failed building manifest: lstat .local: no such file or directory

goroutine 1 [running]:
github.com/nanovms/ops/cmd.runCommandHandler(0xc0000e6280, 0xc0001126f0, 0x1, 0x3)
        /Users/eyberg/go/src/github.com/nanovms/ops/cmd/cmd_run.go:60 +0x48d
github.com/spf13/cobra.(*Command).execute(0xc0000e6280, 0xc000112630, 0x3, 0x3, 0xc0000e6280, 0xc000112630)
        /Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc000339b80, 0x0, 0xffffffff, 0xc00009e058)
        /Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /Users/eyberg/go/src/github.com/nanovms/ops/ops.go:8 +0x2a
➜  test cat config.json
{
  "MapDirs": {
    "/Users/eyberg/.local/*": "/Users/eyberg/.local/"
  }
}
```

**Comment by arknable** [comment]
Also found this issue now
```
panic: interface conversion: interface {} is string, not map[string]interface {}

goroutine 1 [running]:
github.com/nanovms/ops/fs.(*Manifest).AddFileTo(0xc00011c120, 0xc00011c0f0, 0xc000250390, 0x17, 0xc00024c000, 0x49, 0x0, 0x0)
	/home/arknable/Development/Project/nanovms/ops/fs/manifest.go:335 +0x867
github.com/nanovms/ops/fs.(*Manifest).AddFile(...)
	/home/arknable/Development/Project/nanovms/ops/fs/manifest.go:322
github.com/nanovms/ops/lepton.addMappedFiles.func1(0xc00024c000, 0x49, 0x2840300, 0xc0000d7520, 0x0, 0x0, 0x4ed1ce, 0xc0000d7520)
	/home/arknable/Development/Project/nanovms/ops/lepton/image.go:381 +0x450
path/filepath.walk(0xc00024c000, 0x49, 0x2840300, 0xc0000d7520, 0xc00069f058, 0x0, 0x0)
	/opt/go/src/path/filepath/path.go:414 +0x457
path/filepath.walk(0xc000666780, 0x3e, 0x2840300, 0xc0000d6d00, 0xc00069f058, 0x0, 0x0)
	/opt/go/src/path/filepath/path.go:438 +0x31b
path/filepath.walk(0xc0003b9180, 0x39, 0x2840300, 0xc0000d68f0, 0xc00069f058, 0x0, 0x6)
	/opt/go/src/path/filepath/path.go:438 +0x31b
path/filepath.Walk(0xc0003b9180, 0x39, 0xc00069f058, 0x5, 0x0)
	/opt/go/src/path/filepath/path.go:501 +0x113
github.com/nanovms/ops/lepton.addMappedFiles(0xc0003b9180, 0x3a, 0xc00048b940, 0x6, 0x2491cfe, 0x1, 0xc00011c120, 0x0, 0x6)
	/home/arknable/Development/Project/nanovms/ops/lepton/image.go:359 +0x16f
github.com/nanovms/ops/lepton.setManifestFromConfig(0xc00011c120, 0xc00069f478, 0x5, 0x0)
	/home/arknable/Development/Project/nanovms/ops/lepton/image.go:251 +0x234
github.com/nanovms/ops/lepton.BuildManifest(0xc00069f478, 0xc0004fe060, 0x487245, 0x0)
	/home/arknable/Development/Project/nanovms/ops/lepton/image.go:327 +0x2aa
github.com/nanovms/ops/lepton.BuildImage(0xc000074af0, 0x1, 0x1, 0x0, 0x0, 0xc000046450, 0x23, 0x0, 0x0, 0x0, ...)
	/home/arknable/Development/Project/nanovms/ops/lepton/image.go:30 +0x2f
github.com/nanovms/ops/onprem.(*OnPrem).BuildImage(0x37b9470, 0xc000074c00, 0x6, 0x284d340, 0x37b9470, 0xc000074c00)
	/home/arknable/Development/Project/nanovms/ops/onprem/onprem_image.go:17 +0x98
github.com/nanovms/ops/cmd.buildCommandHandler(0xc0002fd180, 0xc0002f3d40, 0x1, 0x3)
	/home/arknable/Development/Project/nanovms/ops/cmd/cmd_build.go:60 +0x2bb
github.com/spf13/cobra.(*Command).execute(0xc0002fd180, 0xc0002f3c80, 0x3, 0x3, 0xc0002fd180, 0xc0002f3c80)
	/home/arknable/Development/libs/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002fcf00, 0x0, 0xffffffff, 0xc0000421d8)
	/home/arknable/Development/libs/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
	/home/arknable/Development/libs/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/home/arknable/Development/Project/nanovms/ops/ops.go:8 +0x2a
```

`config.json` is
```
{
  "MapDirs": {
    "/home/arknable/Development/Project/nanovms/example/hello/*": "/hello"
  }
}
```

I didn't recall this happened before.

**Comment by arknable** [comment]
that's only happened when mapped path is only one root directory, e.g. `/hello` ... otherwise path such as `/example/hello` or deeper is fine.

**Comment by arknable** [comment]
I cannot reproduce this using sample executable
```
arknable@arknable-x1c:~/.../hello$ cat config.json 
{
  "MapDirs": {
    "/home/arknable/Development/Project/nanovms/example/hello/.test/*": "/home/arknable/Development/Project/nanovms/example/hello/.test/"
  }
}arknable@arknable-x1c:~/.../hello$ ls .test/
config.json
arknable@arknable-x1c:~/.../hello$ ops run hello -c config.json
 100% |████████████████████████████████████████|  [0s:0s]
booting /home/arknable/.ops/images/hello.img ...
en1: assigned 10.0.2.15
Server running at http://127.0.0.1:8083/
en1: assigned FE80::34A1:38FF:FE3C:4BEC

```

**Comment by arknable** [comment]
Yup, pretty sure. the dumped fs looks good
```
/
|   lib64
|   |   ld-linux-x86-64.so.2
|   home
|   |   arknable
|   |   |   Development
|   |   |   |   Project
|   |   |   |   |   nanovms
|   |   |   |   |   |   example
|   |   |   |   |   |   |   hello
|   |   |   |   |   |   |   |   .test
|   |   |   |   |   |   |   |   |   config.json
|   .test
|   |   config.json
|   hello
|   lib
|   |   x86_64-linux-gnu
|   |   |   libgcc_s.so.1
|   |   |   libstdc++.so.6
|   |   |   libm.so.6
|   |   |   libpthread.so.0
|   |   |   libdl.so.2
|   |   |   libnss_dns.so.2
|   |   |   librt.so.1
|   |   |   libc.so.6
|   proc
|   |   self
|   |   |   exe -> /hello
|   |   sys
|   |   |   kernel
|   |   |   |   hostname
|   etc
|   |   resolv.conf
|   |   passwd
|   |   ssl
|   |   |   certs
|   |   |   |   ca-certificates.crt

```

**Comment by arknable** [comment]
oh but I can reproduce it if I try to map standard `$HOME/.local` directory
```
arknable@arknable-x1c:~/.../hello$ ops run hello -c config.json 
 100% |████████████████████████████████████████|  [0s:0s]
panic: failed building manifest: lstat .local: no such file or directory

goroutine 1 [running]:
github.com/nanovms/ops/cmd.runCommandHandler(0xc0000eea00, 0xc00032db90, 0x1, 0x3)
	/home/arknable/Development/Project/nanovms/ops/cmd/cmd_run.go:60 +0x48d
github.com/spf13/cobra.(*Command).execute(0xc0000eea00, 0xc00032dad0, 0x3, 0x3, 0xc0000eea00, 0xc00032dad0)
	/home/arknable/Development/libs/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc000334f00, 0x0, 0xffffffff, 0xc000182058)
	/home/arknable/Development/libs/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
	/home/arknable/Development/libs/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/home/arknable/Development/Project/nanovms/ops/ops.go:8 +0x2a

```
