### ISSUE TITLE
ops pkg list [panic] goroutine failure

### ISSUE THREAD

**Issue by optimizasean** [nanovms/ops#1170]
```sh
ops pkg list
failed getting packages: resource not found
panic: failed getting packages: resource not found


goroutine 1 [running]:
github.com/nanovms/ops/log.Panicf(0x31eaca4, 0x1b, 0xc000cbfc50, 0x1, 0x1)
        /Users/eyberg/go/src/github.com/nanovms/ops/log/logger_default.go:91 +0x18a
github.com/nanovms/ops/cmd.cmdListPackages(0xc0005342c0, 0x457c0b8, 0x0, 0x0)
        /Users/eyberg/go/src/github.com/nanovms/ops/cmd/cmd_pkg.go:108 +0xee
github.com/spf13/cobra.(*Command).execute(0xc0005342c0, 0x457c0b8, 0x0, 0x0, 0xc0005342c0, 0x457c0b8)
        /Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001538c0, 0x0, 0xffffffff, 0xc00010e058)
        /Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
        /Users/eyberg/go/src/github.com/nanovms/ops/ops.go:8 +0x2
```

Not sure how I triggered this, just running a bunch of ops pkg list commands...like 20 maybe?  Now it is dead for like 10 minutes.  Was there an update or something that happened about 10 minutes ago?  Works now but...strange...

**Comment by eyberg** [comment]
I think you hit a race between me uploading the package manifest && setting the perms for it to be public which has been noted here, https://github.com/nanovms/ops/blob/master/PACKAGES.md#note , this should go away once we move to a web app in front of the bucket (mainly to allow for public contributions) which is planned but not roadmapped yet - right now it's literally just the bucket
