### ISSUE TITLE
Running Python Streamlit App On Ops Locally

### ISSUE THREAD

**Issue by gfleetwood** [nanovms/ops#1237]
Hi,

I'm trying to convert a streamlit app (initially hosted on Heroku) to running on ops. My machine is running Ubuntu 20.04. In the app folder I first run this setup.sh script:

```
python3 -m venv env
source env/bin/activate
pip install --upgrade pip
pip install -r requirements.txt # only streamlit and requests

mkdir -p .streamlit/
echo "\
[server]\n\
headless = true\n\
port = $PORT\n\
enableCORS = false\n\
\n\
" > .streamlit/config.toml
```

Then my config.json looks like:

```
{
"MapDirs": {
"./env/*": "/.local",
"./.streamlit": "/.streamlit",
"/usr/lib64/*": "/usr/lib/x86_64-linux-gnu"
},
"Dirs": ["usr", "lib"],
"Args": ["streamlit", "run", "app.py"],
"Files": ["app.py"]
}
```

This is the traceback:

```
$ ops pkg load python_3.8.6 -c config.json -p 8501
 100% |████████████████████████████████████████|  [0s:0s]
panic: lstat : no such file or directory

goroutine 1 [running]:
github.com/nanovms/ops/cmd.loadCommandHandler(0xc000612840, 0xc000142870, 0x1, 0x5)
	/Users/eyberg/go/src/github.com/nanovms/ops/cmd/cmd_pkg.go:328 +0x597
github.com/spf13/cobra.(*Command).execute(0xc000612840, 0xc000142820, 0x5, 0x5, 0xc000612840, 0xc000142820)
	/Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:846 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000a3600, 0x0, 0x1f94fe0, 0xc000114058)
	/Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/Users/eyberg/go/src/github.com/nanovms/ops/ops.go:8 +0x2a
```

**Comment by eyberg** [comment]
this error msg could be a bit more helpful but essentially it's not finding a file/directory in your config.json

if you convert the "./env/*" and "./.streamlit" to an absolute path (eg: /my/directory/.env or /my/directory/.streamlit) does that fix your problem?

also the 'usr' and 'lib' - those are directories local to where you are running this?

**Comment by gfleetwood** [comment]
So adding the absolute paths helped - at least the error changed.  And the 'usr' and 'lib' directories I added to the config because I saw it in an article (https://nanovms.com/dev/tutorials/creation-and-usage-of-machine-learning-classification-using-unikernels). I don't actually know what it does. It may be my oversight, but the docs seems pretty sparse and outside of a mailing list and this repo there doesn't seem like a good place for questions.

Turns out my setup.sh can be simpler, so it's now just:

```
python3 -m venv hatata_env
source hatata_env/bin/activate
pip install --upgrade pip
pip install -r requirements.txt
```

And my config.json is now:

```
{
"MapDirs": {
"/home/gordon/workspace/project/env/*": "/.local",
"/usr/lib64/*": "/usr/lib/x86_64-linux-gnu"
},
"Args": ["/.local/bin/streamlit", "run", "app.py"],
"Files": ["app.py"]
}
```

And the current trackback:

```
$ ops pkg load python_3.8.6 -c config.json -p 8501
 100% |████████████████████████████████████████|  [0s:0s]
booting /home/gordon/.ops/images/python3 ...
en1: assigned 10.0.2.15
Traceback (most recent call last):
  File "/.local/bin/streamlit", line 5, in <module>
    from streamlit.cli import main
ModuleNotFoundError: No module named 'streamlit'
```
So it's seems there's some cli portion of the streamlit library that a simple copy paste doesn't replicate.

**Comment by eyberg** [comment]
there's a few things here but this is what worked for me:

```
 ops pkg load python_3.8.6 -c config.json -p 8501
 You are running an older version of Ops.
 Update: Run  `ops update`
booting /home/eyberg/.ops/images/python3 ...
en1: assigned 10.0.2.15
en1: assigned FE80::ACEF:BFFF:FEC2:C613
2022-01-22 17:31:41.740
Warning: the config option 'server.enableCORS=false' is not compatible with 'server.enableXsrfProtection=true'.
As a result, 'server.enableCORS' is being overridden to 'true'.

More information:
In order to protect against CSRF attacks, we send a cookie with each request.
To do so, we must specify allowable origins, which places a restriction on
cross-origin resource sharing.

If cross origin resource sharing is required, please disable server.enableXsrfProtection.

2022-01-22 17:31:42.249 Trying to detect encoding from a tiny portion of (12) byte(s).
2022-01-22 17:31:42.258 ascii passed initial chaos probing. Mean measured chaos is 0.000000 %
2022-01-22 17:31:42.261 ascii is most likely the one. Stopping the process.

  You can now view your Streamlit app in your browser.

  Network URL: http://0.0.0.0:8501
  External URL: http://64.62.249.8:8501

h^Cqemu-system-x86_64: terminating on signal 2
signal: killed
```

1) I just pasted your streamlit config but it was a string so those newlines didn't come through - I just formatted it:

```
cat .streamlit/config.toml
[server]
headless = true
port = 8501
enableCORS = false
```

2) my config:

```
 cat config.json
{
  "MapDirs": {
    "/home/eyberg/pp/hatata_env/*": "/.local"
  },
  "Args": ["/.local/bin/streamlit", "run", "app.py"],
  "Dirs": [".streamlit", "usr", "lib"],
  "Files": ["app.py"]
}```

(you left out the .streamlit folder in what you pasted above)

3) I had to copy a few libraries over - so I just did a 

```
mkdir -p usr/lib/x86_64-linux-gnu
mkdir -p lib/x86_64-linux-gnu
```

then copy the below over - you can use 'locate' if they aren't in those folders already

```
tree usr lib
usr
└── lib
    └── x86_64-linux-gnu
        ├── libffi.so.8
        └── libstdc++.so.6
lib
└── x86_64-linux-gnu
    ├── libbz2.so.1.0
    └── librt.so.1

3 directories, 4 files
```

I would *not* map all of /usr/lib64/* - that is going to copy over a ton of crap and at least in my example I didn't need anything from it

**Comment by eyberg** [comment]
also, on a separate note - we had let the discourse forum lapse and for whatever reason it went away but I re-activated it just now so please feel free to sign up there and use it - you're not the first person that has asked for it

**Comment by gfleetwood** [comment]
So I'm confused about the copying steps:

```
mkdir -p usr/lib/x86_64-linux-gnu
mkdir -p lib/x86_64-linux-gnu
tree usr lib
```

Where is this happening? The shell in the vm? 

Isn't the purpose of the "MapDirs" keys for the config file to take care of the copying?

And just to make sure `"Dirs": [".streamlit", "usr", "lib"]` creates empty directories on the vm? Could you also map the .streamlit directory over?

As a heads-up, the copying of the entire /usr/lib64 directory I took from this example:

https://github.com/nanovms/ops-examples/blob/master/python/python3.8/config.json

**Comment by eyberg** [comment]
in your local dev environment - none of this can actually happen inside the vm

you can definitely do MapDirs but you probably have quite a lot of libraries installed there that you don't need to include in your image - this is just a more precise method

the "Dirs" will copy those local folders from your dev env over into the vm - but it will copy whatever is in them as well - not just create empty folders

in that example they are using a local folder - notice the pre-pending period:

"./usr/lib64/*"

**Comment by gfleetwood** [comment]
Got it. I'm still getting the same error but since my files now mostly match yours I think it may be due to the slight difference that my usr and lib libraries are different versions. I only have `libffi.so.7` for example, and a sudo update and upgrade didn't work on it.

How do you know which usr and lib libraries to copy over?

**Comment by eyberg** [comment]
you should be getting a different msg than the one about streamlit - that you were getting earlier cause you hadn't include the '.streamlit' directory using 'Dirs'

as for knowing which libs it actually wants - it'll tell you that it can't find a library - for instance after nuking my local usr/lib I get this error msg:

```
 ops pkg load python_3.8.6 -c config.json -p 8501
 You are running an older version of Ops.
 Update: Run  `ops update`
booting /home/eyberg/.ops/images/python3 ...
en1: assigned 10.0.2.15
Traceback (most recent call last):
  File "/.local/bin/streamlit", line 5, in <module>
    from streamlit.cli import main
  File "/.local/lib/python3.8/site-packages/streamlit/__init__.py", line 48, in <module>
    from streamlit.proto.RootContainer_pb2 import RootContainer
  File "/.local/lib/python3.8/site-packages/streamlit/proto/RootContainer_pb2.py", line 8, in <module>
    from google.protobuf import reflection as _reflection
  File "/.local/lib/python3.8/site-packages/google/protobuf/reflection.py", line 51, in <module>
    from google.protobuf import message_factory
  File "/.local/lib/python3.8/site-packages/google/protobuf/message_factory.py", line 49, in <module>
    from google.protobuf.internal import python_message as message_impl
  File "/.local/lib/python3.8/site-packages/google/protobuf/internal/python_message.py", line 64, in <module>
    from google.protobuf.internal import extension_dict
  File "/.local/lib/python3.8/site-packages/google/protobuf/internal/extension_dict.py", line 34, in <module>
    from google.protobuf.internal import type_checkers
  File "/.local/lib/python3.8/site-packages/google/protobuf/internal/type_checkers.py", line 48, in <module>
    import ctypes
  File "/usr/local/lib/python3.8/ctypes/__init__.py", line 7, in <module>
    from _ctypes import Union, Structure, Array
ImportError: libffi.so.8: cannot open shared object file: No such file or directory
exit status 3
```

then you can do a 'locate libffi.so.8' to find the library and place it in the location it wants - if you do a 'ops pkg load --trace' it'll show you the paths that the loader is trying to find the library in

ops tries to auto-load anything linked into the actual elf if it finds it (so in this case the python interpreter inside the package) but for libs that get dynamically loaded (like this one) knowledge about the package/application actually needs to be known

**Comment by gfleetwood** [comment]
I had to nuke my virtual env and recreate it to get it to work. I think I may have had to dodge some conda complications as well. I deactivated conda base, went back to the system's default python, and then activated the virtual env.

I also have some questions about using the R package as well, but that'll be a future issue. Now to see if I can deploy this to GCP.

Thanks for the help!

**Comment by eyberg** [comment]
what error are you getting? are you having trouble making http requests in general? dns? ip?

**Comment by gfleetwood** [comment]
Haven't tried the others in ops. The one in my app is a get request. Here's the stack trace. 

```
$ ops pkg load python_3.8.6 -c config.json -p 8501
 100% |████████████████████████████████████████|  [0s:0s]
booting /home/gordon/.ops/images/python3 ...
en1: assigned 10.0.2.15
en1: assigned FE80::5CCC:CFFF:FE0C:D40E
2022-01-22 22:09:50.292 
Warning: the config option 'server.enableCORS=false' is not compatible with 'server.enableXsrfProtection=true'.
As a result, 'server.enableCORS' is being overridden to 'true'.

More information:
In order to protect against CSRF attacks, we send a cookie with each request.
To do so, we must specify allowable origins, which places a restriction on
cross-origin resource sharing.

If cross origin resource sharing is required, please disable server.enableXsrfProtection.
            
2022-01-22 22:10:00.514 Did not auto detect external IP.
Please go to https://docs.streamlit.io/ for debugging hints.

  You can now view your Streamlit app in your browser.

  Network URL: http://0.0.0.0:8501

  For better performance, install the Watchdog module:

  $ pip install watchdog
            
2022-01-22 22:10:10.476 Traceback (most recent call last):
  File "/.local/lib/python3.8/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/.local/lib/python3.8/site-packages/urllib3/util/connection.py", line 72, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/local/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
OSError: [Errno 16] Device or resource busy

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/.local/lib/python3.8/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/local/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/local/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/.local/lib/python3.8/site-packages/urllib3/connection.py", line 205, in connect
    conn = self._new_conn()
  File "/.local/lib/python3.8/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x10c20dbb0>: Failed to establish a new connection: [Errno 16] Device or resource busy

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.local/lib/python3.8/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/.local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/.local/lib/python3.8/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='api.wolframalpha.com', port=80): Max retries exceeded with url: /v2/query?appid=6UX47J-783J4XPTQT&input=solve+2%2A3-4%2A5&podstate=Result__Step-by-step+solution&format=plaintext (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10c20dbb0>: Failed to establish a new connection: [Errno 16] Device or resource busy'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/.local/lib/python3.8/site-packages/streamlit/script_runner.py", line 379, in _run_script
    exec(code, module.__dict__)
  File "/app.py", line 64, in <module>
    soln_steps = read_soln_steps(q)
  File "/app.py", line 42, in read_soln_steps
    r = requests.get("http://api.wolframalpha.com/v2/query?appid={}&input=solve+{}&podstate=Result__Step-by-step+solution&format=plaintext".format(app_id, q))
  File "/.local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/.local/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/.local/lib/python3.8/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/.local/lib/python3.8/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/.local/lib/python3.8/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='api.wolframalpha.com', port=80): Max retries exceeded with url: /v2/query?appid=6UX47J-783J4XPTQT&input=solve+2%2A3-4%2A5&podstate=Result__Step-by-step+solution&format=plaintext (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x10c20dbb0>: Failed to establish a new connection: [Errno 16] Device or resource busy'))
```

**Comment by eyberg** [comment]
I believe you are just having a problem with ssl as I was able to reproduce your issue with https but not http - by default we load certs into /etc/ssl/certs although at least for this python version it looks like it might want them in /usr/lib/ssl instead

you can hack around this (for now) with the following:

```
mkdir -p usr/lib/ssl
cp /etc/ssl/certs/ca-certificates.crt usr/lib/ssl/cert.pem
```

although we can certainly update this package if that's a default that python3.8 expects

**Comment by gfleetwood** [comment]
Doesn't work for me. I'm getting the same error. The only url that brings up the app is http. Changing it to https gives me this error:

```
This site can’t provide a secure connection0.0.0.0 sent an invalid response.
ERR_SSL_PROTOCOL_ERROR
```
