### ISSUE TITLE
writes to /tmp/resolv and should build image directly

### ISSUE THREAD

**Issue by billhuey** [nanovms/ops#196]
```billh@dungeon:~$ ops run hello-world
Downloading.. .staging/mkfs
 271.91 KiB / 271.91 KiB [==================================================================================================================] 100.00% 5.17 MiB/s 0s
Downloading.. .staging/boot.img
 22.50 KiB / 22.50 KiB [====================================================================================================================] 100.00% 9.33 MiB/s 0s
Downloading.. .staging/stage3.img
 1.40 MiB / 1.40 MiB [======================================================================================================================] 100.00% 8.84 MiB/s 0s
panic: open /tmp/resolv: permission denied

goroutine 1 [running]:
github.com/nanovms/ops/lepton.addDNSConfig(0xc00062e060, 0xc000135900)
        /home/billh/go/src/github.com/nanovms/ops/lepton/image.go:55 +0x27c
github.com/nanovms/ops/lepton.addFromConfig(0xc00062e060, 0xc000135900)
        /home/billh/go/src/github.com/nanovms/ops/lepton/image.go:119 +0x106
github.com/nanovms/ops/lepton.BuildManifest(0xc000135900, 0x5, 0x8cc033, 0x4)
        /home/billh/go/src/github.com/nanovms/ops/lepton/image.go:149 +0x1a9
github.com/nanovms/ops/lepton.BuildImage(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/billh/go/src/github.com/nanovms/ops/lepton/image.go:25 +0x2f
main.buildImages(0xc0001529a0)
        /home/billh/go/src/github.com/nanovms/ops/ops.go:143 +0xb8
main.runCommandHandler(0xc00011d180, 0xc0000db110, 0x1, 0x1)
        /home/billh/go/src/github.com/nanovms/ops/ops.go:113 +0x5db
github.com/spf13/cobra.(*Command).execute(0xc00011d180, 0xc0000db0e0, 0x1, 0x1, 0xc00011d180, 0xc0000db0e0)
        /home/billh/go/src/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0xc00018cc80, 0x8, 0x0, 0xc00018c780)
        /home/billh/go/src/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0xc00018cc80, 0xc000135ee8, 0x1)
        /home/billh/go/src/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
        /home/billh/go/src/github.com/nanovms/ops/ops.go:522 +0x1257
billh@dungeon:~$ ll /tmp/resolv 
-rw-r--r-- 1 eyberg eyberg 18 Jan 24 16:54 /tmp/resolv
```

**Comment by billhuey** [comment]
Should be on a per project basis in a .staging directory and not touch a global /tmp directory. It cause races otherwise

**Comment by eyberg** [comment]
to clarify - this isn't just mulit-tenant - also think multi-project - i don't even think a tmp file is needed but if so can just stuff into .staging

**Comment by eyberg** [comment]
also - this isn't just /tmp/resolv - it's also /tmp/hostname

**Comment by anikitenko** [comment]
This issue with `tmp` happens because `/tmp` directory **is not the only one** directory for temp files. This directory should be programmatically determined (`os.TempDir`). On multi-user systems (for example MacOS with 2 users) temp directory could be located at `/var/folders/vg/59fslhy12yg81x72t44twzt80000gn/T/` and Go's built-in function will determine it correctly (as far as I know).

**Comment by eyberg** [comment]
also https://github.com/nanovms/ops/issues/210

**Comment by tijoytom** [comment]
#237
