### ISSUE TITLE
Directory locations problems

### ISSUE THREAD

**Issue by ExternalReality** [nanovms/ops#214]
I am attempting to load a `Sinatra` app. I've started with the simple "hello world" application. Bellow I outline the steps I've taken and the errors I've encountered:

```sh
mkdir ops-sinatra
cd $_
```

Create the `myapp` file:

```ruby
# myapp.rb
require 'sinatra'

get '/' do
  'Hello world!'
end
```

Try to load into ops:
```sh
ops load ruby_2.3.1 -p 4567 -a myapp.rb 
```

We get the following error:
```sh
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- sinatra (LoadError)
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from myapp.rb:2:in `<main>'
exit_group
exit status 1
```

This is OK, we can't find `sinatra`. Let's make a  local `GEM_HOME` and load the `sinatra`:

```bash
mkdir .ruby
export GEM_HOME=.ruby
gem install sinatra
``` 

Now lets make a config file that has the `.ruby` and an environment specify that `.ruby` is our `GEM_HOME`.

```json
{
    "Args": ["myapp.rb"],
    "Dirs": [".ruby"],
    "ENV": {
        "GEM_HOME": ".ruby"
    }
}
```

Great our image knows about `sinatra` now. However there is another problem and here is where I get stuck. Let's run our command:

```sh
ops load ruby_2.3.1 -p 4567 -c config.json
```

and the error:

```sh
/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': libssl.so.1.0.0: cannot open shared object file: No such file or directory - /usr/lib/x86_64-linux-gnu/ruby/2.3.0/openssl.so (LoadError)
```

so `ruby` can't find the shared library its looking for. I've tried the following things to no avail:

- Add `/usr/lib/x86_64-linux-gnu/ruby/2.3.0/` to `Dirs` in `config.json`
- Copy `openssl` to a know good spot like `.ruby`  and add that to `ruby`'s load path. (After this I can see ruby looking in `.ruby` for the shared lib but can't find it still)
- Use `MapsDirs` to try to map the lib directory somewhere else and have `ruby` look in that spot.

I've had no luck with any of the above. Why can ruby find my `GEM_HOME` in the image but not locate the shared lib?

Using ruby to dump the directory tree of the image shows that the shared lib is indeed present in the image (but still ruby won't load it still producing the error above):
```ruby
Dir.glob("**/*/") # for directories
Dir.glob("**/*") # for all files
```

**Comment by tijoytom** [comment]
@ExternalReality thanks, i will take a look.

**Comment by ExternalReality** [comment]
https://github.com/nanovms/ops/issues/240

**Comment by eyberg** [comment]
I added a new ruby 2.5 package last night that addresses all of these concerns - in general these are all what I would label as 'packaging' concerns - 2.3 is also EOL'd

also - i added an example for this here -> https://github.com/nanovms/ops-examples/tree/master/ruby/02-http-hello-world which uncovered a diff. issue but I think this issue is good to go now @ExternalReality ?

**Comment by ExternalReality** [comment]
@eyberg  wonderful thank you.

**Comment by ExternalReality** [comment]
@eyberg I am getting the following when I run the configuration. I am using both the `nightly` image and the `stable` image.

```
== Sinatra (v2.0.5) has taken the stage on 4567 for development with backup from WEBrick
[2019-03-19 19:47:31] INFO  WEBrick::HTTPServer#start: pid=2 port=4567
mmap error: failed to allocate physical memory, size 269557760
mmap error: failed to allocate physical memory, size 269557760
mmap error: failed to allocate physical memory, size 269557760
mmap error: failed to allocate physical memory, size 269557760
mmap error: failed to allocate physical memory, size 269557760
mmap error: failed to allocate physical memory, size 269557760
map() called with unaligned paramters!
 v: 0000000001247000, p: ffffffffffffffff, length: 0000000010112000
exit status 255
```

**Comment by eyberg** [comment]
ehh sorry - i might've pinged you too soon on this - it missed the last night nightly - it should be in tmo

**Comment by eyberg** [comment]
i changed the title of this to reflect what this tkt was at and I think this is solved but I haven't really had time to look into again

**Comment by girish-nanovms** [comment]
I can confirm that with `config.json`
```
{
    "Args": ["myapp.rb", "-o", "0.0.0.0"],
    "Dirs": [".ruby"],
    "ENV": {
        "GEM_HOME": ".ruby"
    }
}
and using this command 
```
ops pkg load --accel=false eyberg/ruby:2.5.1 -p 4567 -c config.json
```

The application is running correctly
```
en1: assigned 10.0.2.15
en1: assigned FE80::48C:30FF:FE6B:E95F
[2022-03-12 11:45:38] INFO  WEBrick 1.4.2
[2022-03-12 11:45:38] INFO  ruby 2.5.1 (2018-03-29) [x86_64-linux-gnu]
== Sinatra (v2.2.0) has taken the stage on 4567 for development with backup from WEBrick
[2022-03-12 11:45:38] INFO  WEBrick::HTTPServer#start: pid=2 port=4567
10.0.2.2 - - [12/Mar/2022:11:45:57 +0000] "GET / HTTP/1.1" 200 12 0.0438
10.0.2.2 - - [12/Mar/2022:11:45:57 UTC] "GET / HTTP/1.1" 200 12
- -> /
10.0.2.2 - - [12/Mar/2022:11:45:58 +0000] "GET /favicon.ico HTTP/1.1" 404 469 0.0081
10.0.2.2 - - [12/Mar/2022:11:45:58 UTC] "GET /favicon.ico HTTP/1.1" 404 469
http://localhost:4567/ -> /favicon.ico
```

**Comment by girish-nanovms** [comment]
We can close this ticket @eyberg
