### ISSUE TITLE
Shared lib not found even though it exists.

### ISSUE THREAD

**Issue by theKAKAN** [nanovms/ops#240]
As the topic says. I'm trying to run [journey](https://github.com/kabukky/journey) which requires libdl.  
I can run `journey` fine using the command line, but when I try to use it through `ops`, it doesn't work and returns that libdl isn't found.  
Here's the debug log:  
```bash
$ ops run journey -d -c ops.json
Finding dependent shared libs
*errors.errorString libdl.so.2: file does not exist
/home/tijoy/go/src/github.com/nanovms/ops/lepton/elf.go:105 (0x767c20)
/home/tijoy/go/src/github.com/nanovms/ops/lepton/elf.go:134 (0x76811d)
/home/tijoy/go/src/github.com/nanovms/ops/lepton/image.go:198 (0x769e5b)
/home/tijoy/go/src/github.com/nanovms/ops/lepton/image.go:24 (0x76894f)
/home/tijoy/go/src/github.com/nanovms/ops/ops.go:220 (0x7d45b2)
/home/tijoy/go/src/github.com/nanovms/ops/ops.go:127 (0x7d294b)
/home/tijoy/go/src/github.com/spf13/cobra/command.go:766 (0x7c8b8c)
/home/tijoy/go/src/github.com/spf13/cobra/command.go:852 (0x7c972d)
/home/tijoy/go/src/github.com/spf13/cobra/command.go:800 (0x7c940b)
/home/tijoy/go/src/github.com/nanovms/ops/ops.go:667 (0x7d980c)
/usr/local/go/src/runtime/proc.go:201 (0x42dcf7)
/usr/local/go/src/runtime/asm_amd64.s:1333 (0x458d61)

panic: libdl.so.2: file does not exist

goroutine 1 [running]:
main.panicOnError(0x93fb40, 0xc00014e1e0)
        /home/tijoy/go/src/github.com/nanovms/ops/ops.go:47 +0xde
main.buildImages(0xc00049c2c0)
        /home/tijoy/go/src/github.com/nanovms/ops/ops.go:221 +0x100
main.runCommandHandler(0xc000142780, 0xc0002a6360, 0x1, 0x2)
        /home/tijoy/go/src/github.com/nanovms/ops/ops.go:127 +0xb0b
github.com/spf13/cobra.(*Command).execute(0xc000142780, 0xc0002a6300, 0x2, 0x2, 0xc000142780, 0xc0002a6300)
        /home/tijoy/go/src/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0xc0004c8280, 0x8, 0x0, 0xc000143b80)
        /home/tijoy/go/src/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0xc0004c8280, 0xc0000e7ec0, 0x1)
        /home/tijoy/go/src/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
        /home/tijoy/go/src/github.com/nanovms/ops/ops.go:667 +0x15bc
```  
However, I'm sure that libdl exists, so I did this in my config.
```json
{
	"MapDirs": {
		"/nix/store/7gx4kiv5m0i7d7qkixq2cwzbr10lvxwc-glibc-2.27/lib/*": "/usr/lib/"
	}
}
```
It doesn't work either.  
```bash
$ ls /nix/store/7gx4kiv5m0i7d7qkixq2cwzbr10lvxwc-glibc-2.27/lib | grep libdl
libdl-2.27.so
libdl.so
libdl.so.2
```
I've glanced at the source code, and it seems like it runs ldd and injects the dependencies itself, which for some reason, doesn't work here.  
And in case this is required:
```
$HOME/.ops
├── 1.0
│   ├── boot.img
│   ├── mkfs
│   ├── nanos-release-linux-1.0.tar.gz
│   └── stage3.img
├── bin
│   └── ops
├── common
├── common.tmp
├── images
│   └── main.img
├── latest.txt
├── ops.sh
└── packages
    └── manifest.json
```  
I use NixOS and have patched the programs accordingly.  
Oh, and the sample golang program seems to run just fine :smile:

**Comment by tijoytom** [comment]
@theKAKAN Can please paste the output from  `ldd journey` on the machine that you are seeing the issue?

**Comment by theKAKAN** [comment]
> @theKAKAN Can please paste the output from `ldd journey` on the machine that you are seeing the issue?

Shit, I forgot that. Sorry, here it is:  
```bash
$ ldd journey
        linux-vdso.so.1 (0x00007ffc354e2000)
        libdl.so.2 => /nix/store/7gx4kiv5m0i7d7qkixq2cwzbr10lvxwc-glibc-2.27/lib/libdl.so.2 (0x00007fb5c1a71000)
        libpthread.so.0 => /nix/store/7gx4kiv5m0i7d7qkixq2cwzbr10lvxwc-glibc-2.27/lib/libpthread.so.0 (0x00007fb5c1852000)
        libc.so.6 => /nix/store/7gx4kiv5m0i7d7qkixq2cwzbr10lvxwc-glibc-2.27/lib/libc.so.6 (0x00007fb5c149e000)
        /nix/store/7gx4kiv5m0i7d7qkixq2cwzbr10lvxwc-glibc-2.27/lib/ld-linux-x86-64.so.2 => /nix/store/7gx4kiv5m0i7d7qkixq2cwzbr10lvxwc-glibc-2.27/lib64/ld-linux-x86-64.so.2 (0x00007fb5c1c75000)
```

**Comment by tijoytom** [comment]
@theKAKAN  this should  fixed now.
