### ISSUE TITLE
loading a missing pkg should tell the user no package exists rather than blowing up

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#254]
this is another one of those dev-ux friendly type of things - if it's not in the manifest just let them know - maybe even ask the user if it should be?

```
➜  ~  ops load ruby_2.3.14234
Downloading.. /Users/eyberg/.ops/packages/ruby_2.3.14234.tar.gz
 224 B / 224 B [====================================================================================================================================================================] 100.00% 28.37 KiB/s 0s
Extracting /Users/eyberg/.ops/packages/ruby_2.3.14234.tar.gz to /Users/eyberg/.ops/.staging/ruby_2.3.14234
panic: gzip: invalid header

goroutine 1 [running]:
github.com/nanovms/ops/lepton.ExtractPackage(0xc000169c00, 0x31, 0xc000187980, 0x1b)
        /home/tijoytom/go/src/github.com/nanovms/ops/lepton/package.go:35 +0x472
main.loadCommandHandler(0xc000568a00, 0xc000286e90, 0x1, 0x1)
        /home/tijoytom/go/src/github.com/nanovms/ops/ops.go:393 +0x2d8
github.com/spf13/cobra.(*Command).execute(0xc000568a00, 0xc000286e60, 0x1, 0x1, 0xc000568a00, 0xc000286e60)
        /home/tijoytom/go/src/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0xc000568f00, 0x8, 0x0, 0xc000568a00)
        /home/tijoytom/go/src/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0xc000568f00, 0xc0000d7ec0, 0x1)
        /home/tijoytom/go/src/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
        /home/tijoytom/go/src/github.com/nanovms/ops/ops.go:689 +0x15bc
```

**Comment by ExternalReality** [comment]
https://github.com/nanovms/ops/pull/270

**Comment by eyberg** [comment]
thanks!
