### ISSUE TITLE
new download seems broken

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#261]
```
➜  vid  ops load node_v11.5.0 -p 8083 -a hi.js
Downloading.. /Users/eyberg/.ops/packages/node_v11.5.0.tar.gz
 15.61 MiB / 15.61 MiB [=============================================================================================================================================================] 100.00% 3.40 MiB/s 4s
Extracting /Users/eyberg/.ops/packages/node_v11.5.0.tar.gz to /Users/eyberg/.ops/.staging/node_v11.5.0
panic: open /Users/eyberg/.ops/.staging/._node_v11.5.0: no such file or directory

goroutine 1 [running]:
github.com/nanovms/ops/lepton.ExtractPackage(0xc0001c3cb0, 0x2f, 0xc000028940, 0x1b)
        /home/tijoytom/go/src/github.com/nanovms/ops/lepton/package.go:61 +0x442
main.loadCommandHandler(0xc000357b80, 0xc0002250e0, 0x1, 0x5)
        /home/tijoytom/go/src/github.com/nanovms/ops/ops.go:393 +0x2d8
github.com/spf13/cobra.(*Command).execute(0xc000357b80, 0xc000225040, 0x5, 0x5, 0xc000357b80, 0xc000225040)
        /home/tijoytom/go/src/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0xc000578280, 0x8, 0x0, 0xc000357b80)
        /home/tijoytom/go/src/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0xc000578280, 0xc0000c1ec0, 0x1)
        /home/tijoytom/go/src/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
        /home/tijoytom/go/src/github.com/nanovms/ops/ops.go:689 +0x15bc
```

@tijoytom - idk if ops needs to be updated or what but this was from a fresh download on the site

**Comment by eyberg** [comment]
fixed via https://github.com/nanovms/ops/pull/262 although not sure why we have a .staging to begin w/ - I thought that got removed a long time ago
