### ISSUE TITLE
eval/fix versioning

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#264]
I noticed earlier when trying to upgrade from 0.1.9 to 0.1.10 it was looking for files that weren't present in 0.1.10 and also the latest.txt was pointing at 0.1.9 after doing an 'ops upgrade' so not sure what the deal is w/that

**Comment by eyberg** [comment]
https://github.com/nanovms/ops/issues/271

**Comment by eyberg** [comment]
this is still a problem - it grabs latest and knows there is a newer version but doesn't grab the new version? lame

```
panic: fork/exec /home/eyberg/.ops/0.1.20/mkfs: no such file or directory

goroutine 1 [running]:
github.com/nanovms/ops/cmd.loadCommandHandler(0xc0004e6c80, 0xc0001d9530, 0x1, 0x3)
        /Users/eyberg/go/src/github.com/nanovms/ops/cmd/load.go:177 +0x1b42
github.com/spf13/cobra.(*Command).execute(0xc0004e6c80, 0xc0001d94a0, 0x3, 0x3, 0xc0004e6c80, 0xc0001d94a0)
        /Users/eyberg/go/src/github.com/spf13/cobra/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001ce000, 0xba1b9c, 0xc0002cbf88, 0xc0000ca058)
        /Users/eyberg/go/src/github.com/spf13/cobra/command.go:852 +0x2c0
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/eyberg/go/src/github.com/spf13/cobra/command.go:800
main.main()
        /Users/eyberg/go/src/github.com/nanovms/ops/ops.go:8 +0x28
eyberg@dungeon:~/j$ ls ~/.ops/
```

**Comment by eyberg** [comment]
old and seems to work so closing

```
eyberg@box:~$ ops version
Ops version: 0.1.9
Nanos version: 0.1.25
eyberg@box:~$ ops update
Checking for updates...
Updates ops to latest release.
eyberg@box:~$ ops version
Ops version: 0.1.10
Nanos version: 0.1.25
```
