### ISSUE TITLE
should only load extra files if present in local dir

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#336]
the new mosquitto pkg tried to overwrite the existing conf file that was inside the pkg w/one that didn't exist - it should only be doing this behavior if there is a conf file added - i think this functionality was originally added for nginx

```
➜  a  ops load mosquitto_1.5.7
Downloading.. https://storage.googleapis.com/packagehub/manifest.json
 3.08 KiB / 3.08 KiB [===============================================================================================================================================================] 100.00% 8.44 MiB/s 0s
Downloading.. https://storage.googleapis.com/packagehub/mosquitto_1.5.7.tar.gz
 3.34 MiB / 3.34 MiB [===============================================================================================================================================================] 100.00% 3.47 MiB/s 0s
warning: overwriting existing file mosquitto.conf hostpath old: /Users/eyberg/.ops/.staging/mosquitto_1.5.7/sysroot/mosquitto.conf new: mosquitto.conf
[mosquitto -c /mosquitto.conf]
2019/05/11 17:28:57 mkfs:metadata (program:mosquitto_1.5.7/mosquitto children:(mosquitto_1.5.7:(children:(mosquitto:() package.manifest:() README:())) lib64:(children:(ld-linux-x86-64.so.2:())) usr:(child
ren:(lib:(children:(x86_64-linux-gnu:(children:(libcrypto.so.1.0.0:() libssl.so.1.0.0:())))))) etc:(children:(resolv.conf:() passwd:())) kernel:() proc:(children:(sys:(children:(kernel:(children:(hostname
:())))))) lib:(children:(x86_64-linux-gnu:(children:(libpthread.so.0:() librt.so.1:() libc.so.6:() libdl.so.2:() libuuid.so.1:() libm.so.6:())))) mosquitto.conf:()) arguments:(1:-c 2:/mosquitto.conf 0:mos
quitto) environment:(USER:root))
couldn't stat file mosquitto.conf: No such file or directory

panic: exit status 2

goroutine 1 [running]:
github.com/nanovms/ops/cmd.loadCommandHandler(0xc0000cf400, 0xc000162360, 0x1, 0x1)
        /Users/eyberg/go/src/github.com/nanovms/ops/cmd/load.go:167 +0x1a35
github.com/spf13/cobra.(*Command).execute(0xc0000cf400, 0xc000162330, 0x1, 0x1, 0xc0000cf400, 0xc000162330)
        /Users/eyberg/go/src/github.com/spf13/cobra/command.go:766 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002a8280, 0x47286f2, 0xc00055df88, 0xc000092058)
        /Users/eyberg/go/src/github.com/spf13/cobra/command.go:852 +0x2c0
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/eyberg/go/src/github.com/spf13/cobra/command.go:800
main.main()
        /Users/eyberg/go/src/github.com/nanovms/ops/ops.go:8 +0x28
➜  a  ls
tempimage
➜  a  vi config
➜  a  vi mosquitto.conf
➜  a  ops load mosquitto_1.5.7
warning: overwriting existing file mosquitto.conf hostpath old: /Users/eyberg/.ops/.staging/mosquitto_1.5.7/sysroot/mosquitto.conf new: mosquitto.conf
[mosquitto -c /mosquitto.conf]
booting /Users/eyberg/.ops/images/mosquitto.img ...
assigned: 10.0.2.15
1557621022: mosquitto version 1.5.7 starting
1557621022: Config loaded from /mosquitto.conf.
1557621022: Opening ipv4 listen socket on port 1883.
1557621022: Opening ipv6 listen socket on port 1883.
1557621022: Warning: Address family not supported by protocol
1557621022: Warning: Mosquitto should not be run as root/administrator.
^Csignal: killed
```

**Comment by ssudake21** [comment]
This seems be a package issue to me.

```
{
   "Program":"mosquitto_1.5.7/mosquitto",
   "Args": ["mosquitto", "-c", "/mosquitto.conf"],
   "Version":"1.5.7",
   "Files": ["mosquitto.conf"]
}
```
We should not have `   "Files": ["mosquitto.conf"]` this line actually in package manifest.

After removing the above line, we should get the expected behavior.

We need to refresh package.manifest with following config,
```~/.ops/.staging/mosquitto_1.5.7/package.manifest 
{
   "Program":"mosquitto_1.5.7/mosquitto",
   "Args": ["mosquitto", "-c", "/mosquitto.conf"],
   "Version":"1.5.7"
}
```

**Comment by ssudake21** [comment]
Additionally, added checks so that we don't ignore missing files. #337

**Comment by ssudake21** [comment]
@eyberg We would need package manifest changes for this.

**Comment by eyberg** [comment]
yeh turns out it's just operator error -thanks for looking into it - i fixed the pkg
