### ISSUE TITLE
should bail out early && fail nicer 

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#389]
```
➜  p  ops instance create -t aws -z us-west1 -i php-image
RequestError: send request failed
caused by: Post https://ec2.us-west1.amazonaws.com/: dial tcp: lookup ec2.us-west1.amazonaws.com: no such host
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x4b687e5]

goroutine 1 [running]:
github.com/nanovms/ops/lepton.(*AWS).CreateInstance(0xc0000ac0d0, 0xc000368680, 0x5259be0, 0xc0000ac0d0)
        /Users/eyberg/go/src/github.com/nanovms/ops/lepton/aws.go:332 +0xa5
github.com/nanovms/ops/cmd.instanceCreateCommandHandler(0xc000260280, 0xc0000927e0, 0x0, 0x6)
        /Users/eyberg/go/src/github.com/nanovms/ops/cmd/instance.go:56 +0x2fd
github.com/spf13/cobra.(*Command).execute(0xc000260280, 0xc0000926c0, 0x6, 0x6, 0xc000260280, 0xc0000926c0)
        /Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001e6a00, 0x4bc8f37, 0xc0005e5f88, 0xc000094058)
        /Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2bb
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /Users/eyberg/go/src/github.com/nanovms/ops/ops.go:8 +0x28
```

instead of throwing this trace it should give a polite msg to the user stating that the region is unknown

**Comment by chaitanya-baraskar** [comment]
I will start looking into this issue.

**Comment by eyberg** [comment]
not sure where this was fixed but this is now working as expected
