### ISSUE TITLE
version check prevents offline usage

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#395]
someone brought this up before and I just experienced it myself when doing an offline demo - an inelegant solution i'd propose is to keep the version check but fail gracefully if you're not online maybe by issuing a log line stating you're offline, i believe the original assumption still stands that no internet makes jack a dull boy though

**Comment by eyberg** [comment]
well i tried this w/a sample go app and that seems to revert to local ->

```
➜  t  ops run t
version lookup failed, using local.
booting /Users/eyberg/.ops/images/t.img ...
assigned: 10.0.2.15
yo
exit status 1
```

maybe pkgs has this problem?

**Comment by eyberg** [comment]
yep - it's a pkg that has problems w/being offline ->

```
➜  j  ops load node_v13.6.0 -p 8083 -a hi.js
version lookup failed, using local.
panic: Head https://storage.googleapis.com/packagehub/manifest.json: dial tcp: lookup storage.googleapis.com: no such host

goroutine 1 [running]:
github.com/nanovms/ops/lepton.PackageManifestChanged(0x53a9920, 0xc00038a270, 0x51777a7, 0x37, 0x0)
        /Users/eyberg/go/src/github.com/nanovms/ops/lepton/package.go:91 +0xa4
github.com/nanovms/ops/lepton.GetPackageList(0x2f30000000000028)
        /Users/eyberg/go/src/github.com/nanovms/ops/lepton/package.go:54 +0x22a
github.com/nanovms/ops/lepton.DownloadPackage(0x7ffeefbff989, 0xc, 0x2, 0xc00002e2a0, 0x28, 0xc000377540)
        /Users/eyberg/go/src/github.com/nanovms/ops/lepton/package.go:34 +0x34
github.com/nanovms/ops/cmd.downloadAndExtractPackage(0x7ffeefbff989, 0xc, 0x5, 0x0)
        /Users/eyberg/go/src/github.com/nanovms/ops/cmd/utils.go:152 +0x1d3
github.com/nanovms/ops/cmd.loadCommandHandler(0xc000380a00, 0xc0003581e0, 0x1, 0x5)
        /Users/eyberg/go/src/github.com/nanovms/ops/cmd/load.go:123 +0xed
github.com/spf13/cobra.(*Command).execute(0xc000380a00, 0xc000358190, 0x5, 0x5, 0xc000380a00, 0xc000358190)
        /Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc000022500, 0x4ca8d37, 0xc0002fff88, 0xc000094058)
        /Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2bb
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /Users/eyberg/go/src/github.com/nanovms/ops/ops.go:8 +0x28
```

**Comment by eyberg** [comment]
https://github.com/nanovms/ops/pull/452
