### ISSUE TITLE
net command not working

### ISSUE THREAD

**Issue by francopeapea** [nanovms/ops#402]
```
sh-3.2# ../ops/ops net setup
sh-3.2# ../ops/ops net reset
panic: not implemented

goroutine 1 [running]:
github.com/nanovms/ops/cmd.netResetCommandHandler(0xc0001df900, 0x5abf390, 0x0, 0x0)
	/ops/cmd/net.go:34 +0xb5
github.com/spf13/cobra.(*Command).execute(0xc0001df900, 0x5abf390, 0x0, 0x0, 0xc0001df900, 0x5abf390)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001de000, 0x0, 0x55000, 0xc000092058)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/ops/ops.go:8 +0x27
```

Not understanding the usage of net or net not working properly:

```
bash-3.2$ ../ops/ops load node_v11.5.0 -c config.json -b -a test/hi.js 
[node test/hi.js]
booting /.ops/images/node.img ...
qemu-system-x86_64: could not open /dev/tap0: No such file or directory
exit status 1
```

**Comment by eyberg** [comment]
i'm not sure about the status of the net setup && reset commands as I never use them - this prob. needs a bit more information/enumeration of what's going on - for sure it shouldn't panic w/out explaining what's up

**Comment by fabioDMFerreira** [comment]
Network operations are handled in other commands. 

`ops net` commands were deprecated.
