### ISSUE TITLE
panic when passed an incorrect image for aws

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#426]
it should give the human a more friendly reason why it failed

```
eyberg@box:~/tea$ ops image delete node-image -z us-west-1 -t aws
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/nanovms/ops/lepton.(*AWS).DeleteImage(0xc00000e200, 0xc0005a0110, 0x7ffec24681b2, 0xa, 0x9, 0x0)
        /Users/eyberg/go/src/github.com/nanovms/ops/lepton/aws.go:330 +0x9d4
github.com/nanovms/ops/cmd.imageDeleteCommandHandler(0xc000267400, 0xc0004dd3b0, 0x1, 0x5)
        /Users/eyberg/go/src/github.com/nanovms/ops/cmd/image.go:181 +0x1a3
github.com/spf13/cobra.(*Command).execute(0xc000267400, 0xc0004dd360, 0x5, 0x5, 0xc000267400, 0xc0004dd360)
        /Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000d3900, 0x1113461, 0xc000411f88, 0xc0000c2058)
        /Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2bb
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /Users/eyberg/go/src/github.com/nanovms/ops/ops.go:8 +0x28
```

**Comment by chaitanya-baraskar** [comment]
I have started looking in to this issue.

**Comment by chaitanya-baraskar** [comment]
I tested this issue and I also checked code. It's working as expected. I got following error when I tried to delete already deleted image  "Error running deregister image operation: image main-image1601882574417833695 not found"

**Comment by eyberg** [comment]
k, old, closing
