### ISSUE TITLE
ops should give a friendlier error msg for not being able to find a file

### ISSUE THREAD

**Issue by eyberg** [nanovms/ops#433]
(eg: don't panic) - just tell the user that it can't find the file

```
panic: stat start.jar: no such file or directory

goroutine 1 [running]:
github.com/nanovms/ops/cmd.loadCommandHandler(0xc000033680, 0xc00028cbd0, 0x1, 0x3)
        /Users/eyberg/go/src/github.com/nanovms/ops/cmd/load.go:183 +0x1b42
github.com/spf13/cobra.(*Command).execute(0xc000033680, 0xc00028cae0, 0x3, 0x3, 0xc000033680, 0xc00028cae0)
        /Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2ae
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000d3900, 0x1113461, 0xc000413f88, 0xc0000c2058)
        /Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2bb
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/eyberg/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /Users/eyberg/go/src/github.com/nanovms/ops/ops.go:8 +0x28
```

**Comment by eyberg** [comment]
https://github.com/nanovms/ops/pull/453
