### ISSUE TITLE
MapDirs not creating empty directories

### ISSUE THREAD

**Issue by alextsak** [nanovms/ops#441]
First of all, very nice work!

I have written a simple cpp program that reads data from a file (src.txt) and writes them to a new one (out.txt). 
I run it using the following command ("test" is the name of the executable). 

`ops run -c config.json test`

And my config.json
```
{
    "Files":["test"],
    "Args":["test"],
    "MapDirs":{"/home/alex/cppprojects/testproject/data/*":"/data"} 
}
 ```
Even though the unikernel exits successfully and opens the file to read the data from the mapped directory (/data), the new file is not created.

Does OPS support storing new files from guest or does it somehow offer a way to mount a block device to the guest and store files there?

**Comment by eyberg** [comment]
we don't have support for extra block devices yet (although that's def roadmapped) - however you most definitely should be able to create new files in the guest fs

my guess here is that a directory is being assumed to exist (maybe /tmp ?) and it's not and the directory itself is not being created thus the file is not being created - you can use the 'Dirs' config to include any missing dirs and create whatever your root fs is supposed to look like in your scratch dir if necessary - to really get to the bottom of the issue you'll need to see where it fails

you can turn on strace style output using '-d' w/ops and it should pinpoint which file is failing to be created

**Comment by alextsak** [comment]
Thanks for the reply.
I changed my sample app to only write a string to an output file as the read procedure works fine.
My dir structure is the following:

```
/data
    /out
```

and the config:
```
{
    "Files":["test"],
    "Args":["test"],
    "Dir":["data"],
    "MapDirs":{"/home/alex/cprojects/image-processing/stbiproc/data/*":"/data"}
} 
```

I am putting only the root folder (data) based on the OPS documentation (I have tried to add also the data/out directory but with no result). 
I also noticed that if the "out" directory does not contain any file inside then I get the following error:

``` 
filesystem_mkentry error: a path component ("out") is missing
```
However, if I create a sample file inside the directory then no errors are being thrown which is weird.
 
Nevertheless the output file is not created inside the data/out directory as it was supposed to. You can see the strace below:

```
[test]
booting /home/alex/.ops/images/test.img ...
assigned: 10.0.2.15
read program complete: 0x0000020000000000 gitversion: ea92930270a68eec22d9353bee9cb330e9f74ef9 1 run frame 0x0000000101201000, RIP=0x0000000500001090
1 brk
1 direct return: 10268672, rsp 0x76c21e18
1 uname
1 direct return: 0, rsp 0x76c21a38
1 access
1 access: "/etc/ld.so.nohwcap", mode 0
1 direct return: -2, rsp 0x76c21b10
1 access
1 access: "/etc/ld.so.preload", mode 4
1 direct return: -2, rsp 0x76c21c28
1 openat
1 "/etc/ld.so.cache" - not found
1 direct return: -2, rsp 0x76c21468
1 openat
1 "/lib/x86_64-linux-gnu/tls/x86_64/libstdc++.so.6" - not found
1 direct return: -2, rsp 0x76c21388
1 stat
1 stat: "/lib/x86_64-linux-gnu/tls/x86_64", buf 0x0000000076c214d0
1 direct return: -2, rsp 0x76c21408
1 openat
1 "/lib/x86_64-linux-gnu/tls/libstdc++.so.6" - not found
1 direct return: -2, rsp 0x76c21388
1 stat
1 stat: "/lib/x86_64-linux-gnu/tls", buf 0x0000000076c214d0
1 direct return: -2, rsp 0x76c21408
1 openat
1 "/lib/x86_64-linux-gnu/x86_64/libstdc++.so.6" - not found
1 direct return: -2, rsp 0x76c21388
1 stat
1 stat: "/lib/x86_64-linux-gnu/x86_64", buf 0x0000000076c214d0
1 direct return: -2, rsp 0x76c21408
1 openat
1 "/lib/x86_64-linux-gnu/libstdc++.so.6" - not found
1 direct return: -2, rsp 0x76c21388
1 stat
1 stat: "/lib/x86_64-linux-gnu", buf 0x0000000076c214d0
1 st_ino 20000000b40, st_mode 0x41ff, st_size 0
1 direct return: 0, rsp 0x76c21408
1 openat
1 "/usr/lib/x86_64-linux-gnu/tls/x86_64/libstdc++.so.6" - not found
1 direct return: -2, rsp 0x76c21388
1 stat
1 stat: "/usr/lib/x86_64-linux-gnu/tls/x86_64", buf 0x0000000076c214d0
1 direct return: -2, rsp 0x76c21408
1 openat
1 "/usr/lib/x86_64-linux-gnu/tls/libstdc++.so.6" - not found
1 direct return: -2, rsp 0x76c21388
1 stat
1 stat: "/usr/lib/x86_64-linux-gnu/tls", buf 0x0000000076c214d0
1 direct return: -2, rsp 0x76c21408
1 openat
1 "/usr/lib/x86_64-linux-gnu/x86_64/libstdc++.so.6" - not found
1 direct return: -2, rsp 0x76c21388
1 stat
1 stat: "/usr/lib/x86_64-linux-gnu/x86_64", buf 0x0000000076c214d0
1 direct return: -2, rsp 0x76c21408
1 openat
1    fd 3, length 1594864, offset 0
1 direct return: 3, rsp 0x76c21388
1 read
1 file_read: f 0x0000000101800210, dest 0x0000000076c21638, offset 0 (file), length 832, file length 1594864
1 sleep uninterruptible
1 file_op_complete: len 832, status (none) (OK)
1 thread_wakeup: 1->1 blocked_on uninterruptible, RIP=0x50001cda4
1 run frame 0x0000000101201000, RIP=0x000000050001cda4
1 fstat
1 fd 3, stat 0x0000000076c214d0
1 st_ino 200000007c0, st_mode 0x81a4, st_size 1855f0
1 direct return: 0, rsp 0x76c21448
1 mmap
1 mmap: target 0x0000000000000000, size 0x2000, len 0x2000, prot 0x3, flags 0x22, fd -1, offset 0x0
1    anon target: 0x70f6a48000, len: 0x2000 (given size: 0x2000)
1 direct return: 485174312960, rsp 0x76c21388
1 mmap
1 mmap: target 0x0000000000000000, size 0x388040, len 0x389000, prot 0x5, flags 0x802, fd 3, offset 0x0
1   read file at 0x70a1000000, flen 1597440, blocking...
1 sleep uninterruptible
1 thread_wakeup: 1->1 blocked_on uninterruptible, RIP=0x50001cf43
1 run frame 0x0000000101201000, RIP=0x000000050001cf43
1 mprotect
1 mprotect: addr 0x00000070a1179000, len 0x200000, prot 0x0
1 direct return: 0, rsp 0x76c212b8
1 mmap
1 mmap: target 0x00000070a1379000, size 0xc000, len 0xc000, prot 0x3, flags 0x812, fd 3, offset 0x179000
1   read file at 0x70a1379000, flen 49152, blocking...
1 sleep uninterruptible
1 thread_wakeup: 1->1 blocked_on uninterruptible, RIP=0x50001cf43
1 run frame 0x0000000101201000, RIP=0x000000050001cf43
1 mmap
1 mmap: target 0x00000070a1385000, size 0x3040, len 0x4000, prot 0x3, flags 0x32, fd -1, offset 0x0
1    anon target: 0x70a1385000, len: 0x4000 (given size: 0x3040)
1 direct return: 483741159424, rsp 0x76c21288
1 close
1 close: fd 3
1 direct return: 0, rsp 0x76c21448
1 openat
1    fd 3, length 96616, offset 0
1 direct return: 3, rsp 0x76c21358
1 read
1 file_read: f 0x0000000101800210, dest 0x0000000076c21608, offset 0 (file), length 832, file length 96616
1 sleep uninterruptible
1 file_op_complete: len 832, status (none) (OK)
1 thread_wakeup: 1->1 blocked_on uninterruptible, RIP=0x50001cda4
1 run frame 0x0000000101201000, RIP=0x000000050001cda4
1 fstat
1 fd 3, stat 0x0000000076c214a0
1 st_ino 20000000c00, st_mode 0x81a4, st_size 17968
1 direct return: 0, rsp 0x76c21418
1 mmap
1 mmap: target 0x0000000000000000, size 0x217430, len 0x218000, prot 0x5, flags 0x802, fd 3, offset 0x0
1   read file at 0x70c4400000, flen 98304, blocking...
1 sleep uninterruptible
1 thread_wakeup: 1->1 blocked_on uninterruptible, RIP=0x50001cf43
1 run frame 0x0000000101201000, RIP=0x000000050001cf43
1 mprotect
1 mprotect: addr 0x00000070c4417000, len 0x1ff000, prot 0x0
1 direct return: 0, rsp 0x76c212b8
1 mmap
1 mmap: target 0x00000070c4616000, size 0x2000, len 0x2000, prot 0x3, flags 0x812, fd 3, offset 0x16000
1   read file at 0x70c4616000, flen 8192, blocking...
1 sleep uninterruptible
1 thread_wakeup: 1->1 blocked_on uninterruptible, RIP=0x50001cf43
1 run frame 0x0000000101201000, RIP=0x000000050001cf43
1 close
1 close: fd 3
1 direct return: 0, rsp 0x76c21418
1 openat
1    fd 3, length 2030544, offset 0
1 direct return: 3, rsp 0x76c21338
1 read
1 file_read: f 0x0000000101800210, dest 0x0000000076c215d8, offset 0 (file), length 832, file length 2030544
1 sleep uninterruptible
1 file_op_complete: len 832, status (none) (OK)
1 thread_wakeup: 1->1 blocked_on uninterruptible, RIP=0x50001cda4
1 run frame 0x0000000101201000, RIP=0x000000050001cda4
1 fstat
1 fd 3, stat 0x0000000076c21470
1 st_ino 20000000c80, st_mode 0x81a4, st_size 1efbd0
1 direct return: 0, rsp 0x76c213e8
1 mmap
1 mmap: target 0x0000000000000000, size 0x3f0ae0, len 0x3f1000, prot 0x5, flags 0x802, fd 3, offset 0x0
1   read file at 0x7084c00000, flen 2031616, blocking...
1 sleep uninterruptible
1 thread_wakeup: 1->1 blocked_on uninterruptible, RIP=0x50001cf43
1 run frame 0x0000000101201000, RIP=0x000000050001cf43
1 mprotect
1 mprotect: addr 0x0000007084de7000, len 0x200000, prot 0x0
1 direct return: 0, rsp 0x76c211f8
1 mmap
1 mmap: target 0x0000007084fe7000, size 0x6000, len 0x6000, prot 0x3, flags 0x812, fd 3, offset 0x1e7000
1   read file at 0x7084fe7000, flen 24576, blocking...
1 sleep uninterruptible
1 thread_wakeup: 1->1 blocked_on uninterruptible, RIP=0x50001cf43
1 run frame 0x0000000101201000, RIP=0x000000050001cf43
1 mmap
1 mmap: target 0x0000007084fed000, size 0x3ae0, len 0x4000, prot 0x3, flags 0x32, fd -1, offset 0x0
1    anon target: 0x7084fed000, len: 0x4000 (given size: 0x3ae0)
1 direct return: 483267629056, rsp 0x76c211c8
1 close
1 close: fd 3
1 direct return: 0, rsp 0x76c213e8
1 openat
1    fd 3, length 1700792, offset 0
1 direct return: 3, rsp 0x76c211e8
1 read
1 file_read: f 0x0000000101800210, dest 0x0000000076c21488, offset 0 (file), length 832, file length 1700792
1 sleep uninterruptible
1 file_op_complete: len 832, status (none) (OK)
1 thread_wakeup: 1->1 blocked_on uninterruptible, RIP=0x50001cda4
1 run frame 0x0000000101201000, RIP=0x000000050001cda4
1 fstat
1 fd 3, stat 0x0000000076c21320
1 st_ino 20000000bc0, st_mode 0x81a4, st_size 19f3b8
1 direct return: 0, rsp 0x76c21298
1 mmap
1 mmap: target 0x0000000000000000, size 0x39d158, len 0x39e000, prot 0x5, flags 0x802, fd 3, offset 0x0
1   read file at 0x7039c00000, flen 1703936, blocking...
1 sleep uninterruptible
1 thread_wakeup: 1->1 blocked_on uninterruptible, RIP=0x50001cf43
1 run frame 0x0000000101201000, RIP=0x000000050001cf43
1 mprotect
1 mprotect: addr 0x0000007039d9d000, len 0x1ff000, prot 0x0
1 direct return: 0, rsp 0x76c21138
1 mmap
1 mmap: target 0x0000007039f9c000, size 0x2000, len 0x2000, prot 0x3, flags 0x812, fd 3, offset 0x19c000
1   read file at 0x7039f9c000, flen 8192, blocking...
1 sleep uninterruptible
1 thread_wakeup: 1->1 blocked_on uninterruptible, RIP=0x50001cf43
1 run frame 0x0000000101201000, RIP=0x000000050001cf43
1 close
1 close: fd 3
1 direct return: 0, rsp 0x76c21298
1 mmap
1 mmap: target 0x0000000000000000, size 0x2000, len 0x2000, prot 0x3, flags 0x22, fd -1, offset 0x0
1    anon target: 0x70a0aec000, len: 0x2000 (given size: 0x2000)
1 direct return: 483732144128, rsp 0x76c21a98
1 arch_prctl
1 arch_prctl: code 0x1002, addr 0x70a0aecd80
1 direct return: 0, rsp 0x76c21c20
1 mprotect
1 mprotect: addr 0x0000007084fe7000, len 0x4000, prot 0x1
1 direct return: 0, rsp 0x76c21b08
1 mprotect
1 mprotect: addr 0x0000007039f9c000, len 0x1000, prot 0x1
1 direct return: 0, rsp 0x76c21b08
1 mprotect
1 mprotect: addr 0x00000070c4616000, len 0x1000, prot 0x1
1 direct return: 0, rsp 0x76c21b08
1 mmap
1 mmap: target 0x0000000000000000, size 0x2000, len 0x2000, prot 0x3, flags 0x22, fd -1, offset 0x0
1    anon target: 0x700b186000, len: 0x2000 (given size: 0x2000)
1 direct return: 481222483968, rsp 0x76c218d8
1 mprotect
1 mprotect: addr 0x00000070a1379000, len 0xa000, prot 0x1
1 direct return: 0, rsp 0x76c21b08
1 mprotect
1 mprotect: addr 0x000000000078d000, len 0x1000, prot 0x1
1 direct return: 0, rsp 0x76c21b08
1 mprotect
1 mprotect: addr 0x0000000500227000, len 0x1000, prot 0x1
1 direct return: 0, rsp 0x76c21b08
1 brk
1 direct return: 10268672, rsp 0x76c21d18
1 brk
1 direct return: 10403840, rsp 0x76c21d18
1 fstat
1 fd 1, stat 0x0000000076c21a70
1 st_ino 0, st_mode 0x1000, st_size 0
1 direct return: 0, rsp 0x76c21a68
1 openat
1    fd 3, length 0, offset 0
1 direct return: 3, rsp 0x76c21a50
1 write
1 file_write: f 0x0000000101800210, dest 0x00000000009df0e0, offset 0 (file), length 31, file length 0
1 file_write: b_ref: 0x000000010040bae0
1 sleep uninterruptible
1 file_op_complete: len 31, status (none) (OK)
1 thread_wakeup: 1->1 blocked_on uninterruptible, RIP=0x7084d10154
1 run frame 0x0000000101201000, RIP=0x0000007084d10154
1 close
1 close: fd 3
1 direct return: 0, rsp 0x76c21b58
1 write
Starting program...
Data written to file!
1 direct return: 42, rsp 0x76c21d18
1 exit_group
exit status 1
```
I am putting below the code that I am using in case I have something wrong in my output path.

```
#include <fstream>  
#include <iostream>  
#include <string>  

int main(int argc, char **argv){
    printf("Starting program...\n");
    std::string s="hello world - some random text\n";  
    std::ofstream os("/data/out/test1.txt");  
    if (!os) { 
        std::cerr<<"Error writing data..."<<std::endl; 
    } else {  
        os << s;  
        printf("Data written to file!\n");
    }  

    return 0;
}

```

**Comment by eyberg** [comment]
'Dir' should be named 'Dirs' (and prob. best to pick one of those) - maybe we should create an issue for invalid keys found or something

I was able to write out via this ->

```
eyberg@x:~/z$ ops run main -c config.json
booting /home/eyberg/.ops/images/main.img ...
qemu-system-x86_64: warning: TCG doesn't support requested feature: CPUID.01H:ECX.vmx [bit 5]
assigned: 10.0.2.15
Starting program...
Data written to file!
exit status 1
eyberg@x:~/z$ cat config.json
{
    "Dirs":["data"]
}
eyberg@x:~/z$ cat main.cpp
#include <fstream>
#include <iostream>
#include <string>

int main(int argc, char **argv){
    printf("Starting program...\n");
    std::string s="hello world - some random text\n";
    std::ofstream os("/data/out/test1.txt");
    if (!os) {
        std::cerr<<"Error writing data..."<<std::endl;
    } else {
        os << s;
        printf("Data written to file!\n");
    }

    return 0;
}
eyberg@x:~/z$ tree
.
├── config.json
├── data
│   └── out
├── main
└── main.cpp

2 directories, 3 files
```

it seems fine with 'Dirs' but not 'MapDirs' - the latter is usually used for large nested folders (eg: /usr/local/blah) - also - I *believe* this is an ops issue not a nanos issue but will need to investigate sometime next week

**Comment by eyberg** [comment]
also - a few things about your code:

* don't forget to close() out that file as it will force a write flush - no guarantees if this is not done and the program exits early

* if you throw the open file into append mode (std::ios_base::app) you can see successive writes via this ->

```
eyberg@x:~/z$ strings ~/.ops/images/main.img | grep "hello world"
hello world - some random text
hello world - some random text
hello world - some random text
hello world - some random text
hello world - some random text
```

and requesting not to rebuild the image ->

```
ops run -s
```

**Comment by eyberg** [comment]
just following up on this - I believe https://github.com/nanovms/ops/blob/cf8eec9c4af60bf6fa4233c8e98d8128bb22f5df/lepton/image.go#L278-L280 needs to be refactored to take into account empty dirs

**Comment by arknable** [comment]
@eyberg I don't think there is an issue with `MapDirs` because it should be used to map local path. If I only have `data` folder in my local, the app failed to write `test1.txt` which I think should be expected as `out` directory is not exists and the application does not create it. But then if I added empty `out` directory in my local `data` directory, the application successfully write to `test1.txt`. So I think that should be expected.

What I think is unexpected is if I specify following config:
```
{
    "Dirs":["data/out"]
}
```

`run` command panic
```
panic: failed building manifest: lstat data/out: no such file or directory

goroutine 1 [running]:
github.com/nanovms/ops/cmd.runCommandHandler(0xc0005e6a00, 0xc00007fcb0, 0x1, 0x3)
	/home/arknable/Development/Project/nanovms/ops/cmd/cmd_run.go:60 +0x48d
github.com/spf13/cobra.(*Command).execute(0xc0005e6a00, 0xc00007fbf0, 0x3, 0x3, 0xc0005e6a00, 0xc00007fbf0)
	/home/arknable/Development/libs/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc0002c4500, 0x0, 0xffffffff, 0xc0000421d8)
	/home/arknable/Development/libs/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x30b
github.com/spf13/cobra.(*Command).Execute(...)
	/home/arknable/Development/libs/gopath/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
	/home/arknable/Development/Project/nanovms/ops/ops.go:8 +0x2a
```

but not this
```
{
    "Dirs":["data"]
}
```

so I think `Dirs` need to make sure the created path is recursive. what do you think ?

**Comment by eyberg** [comment]
no, including the top-level directory is fine

the above example code looks like it's still failing for me with MapDirs but is fine with Dirs

```
eyberg@s1:~/z$ ops run -c config.json main
booting /home/eyberg/.ops/images/main.img ...
en1: assigned 10.0.2.15
Starting program...
Error writing data...
eyberg@s1:~/z$ cat config.json
{
  "MapDirs":{"/home/eyberg/z/data/*":"/data"}
}
eyberg@s1:~/z$ tree data/
data/
└── out

1 directory, 0 files
```

it's actually not even including the parent directory if it's just dirs ->

```
eyberg@s1:~/z$ ~/.ops/0.1.34/dump -t ~/.ops/images/main.img
detected filesystem at 0xc0e800
Label:
UUID: ba5c9c95-63e9-06c3-4879-c5b9e270a481
metadata
....*snip*.....
/
|   lib
|   |   x86_64-linux-gnu
|   |   |   libm.so.6
|   |   |   libc.so.6
|   |   |   libnss_dns.so.2
|   |   |   libgcc_s.so.1
|   proc
|   |   sys
|   |   |   kernel
|   |   |   |   hostname
|   |   self
|   |   |   exe -> /main
|   usr
|   |   lib
|   |   |   x86_64-linux-gnu
|   |   |   |   libstdc++.so.6
|   etc
|   |   resolv.conf
|   |   passwd
|   |   ssl
|   |   |   certs
|   |   |   |   ca-certificates.crt
|   main
|   lib64
|   |   ld-linux-x86-64.so.2
```

**Comment by eyberg** [comment]
you can see after adding just a single file to make it non-empty it works ->

```
eyberg@s1:~/z$ ops run -c config.json main
booting /home/eyberg/.ops/images/main.img ...
en1: assigned 10.0.2.15
create_extent error: out of storage allocating 8 blocks
Starting program...
Data written to file!
```

**Comment by arknable** [comment]
OK understood, I found the cause
