### ISSUE TITLE
Cannot allocate memory

### ISSUE THREAD

**Issue by Dmitry-N-Medvedev** [nanovms/ops#519]
hi,

I am starting a NodeJS v14.2.0 unikernel with the following settings:

```json
{
  "Dirs": [
    "/install-root"
  ],
  "Args": [
    "--trace-warnings",
    "--inspect=0.0.0.0:9229",
    "--inspect-brk=0.0.0.0:9229",
    "/install-root/sources/services/authswitch/authswitch.mjs"
  ],
  "Env": {
    "Environment": "development",
    "NODE_DEBUG": "*",
    "NODE_DEBUG_NATIVE": "*",
    "REDIS_HOST": "127.0.0.1",
    "REDIS_PORT": "6379"
  },
  "NameServer": "8.8.8.8",
  "RunConfig": {
    "Ports": [
      9229
    ],
    "Verbose": true
  },
  "CloudConfig": {
    "BucketName": "authswitch"
  },
  "RebootOnExit": false
}
```

...and this gives me the following error:

```bash
(node:2) UnhandledPromiseRejectionWarning: Error: Error: Cannot allocate memory
    at Redis.connect (/install-root/node_modules/.pnpm/registry.npmjs.org/redis-fast-driver/2.1.5/node_modules/redis-fast-driver/index.js:49:26)
    at file:///install-root/sources/libs/redis/libredis/libredis.mjs:21:7
    at new Promise (<anonymous>)
    at startRedis (file:///install-root/sources/libs/redis/libredis/libredis.mjs:5:42)
    at LibAuthSwitch.start (file:///install-root/sources/libs/redis/libauthswitch/libauthswitch.mjs:91:28)
    at file:///install-root/sources/services/authswitch/authswitch.mjs:119:17
    at file:///install-root/sources/services/authswitch/authswitch.mjs:120:3
    at ModuleJob.run (internal/modules/esm/module_job.js:110:37)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
    at emitUnhandledRejectionWarning (internal/process/promises.js:149:15)
    at processPromiseRejections (internal/process/promises.js:211:11)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
(node:2) Error: Error: Cannot allocate memory
    at Redis.connect (/install-root/node_modules/.pnpm/registry.npmjs.org/redis-fast-driver/2.1.5/node_modules/redis-fast-driver/index.js:49:26)
    at file:///install-root/sources/libs/redis/libredis/libredis.mjs:21:7
    at new Promise (<anonymous>)
    at startRedis (file:///install-root/sources/libs/redis/libredis/libredis.mjs:5:42)
    at LibAuthSwitch.start (file:///install-root/sources/libs/redis/libauthswitch/libauthswitch.mjs:91:28)
    at file:///install-root/sources/services/authswitch/authswitch.mjs:119:17
    at file:///install-root/sources/services/authswitch/authswitch.mjs:120:3
    at ModuleJob.run (internal/modules/esm/module_job.js:110:37)
    at async Loader.import (internal/modules/esm/loader.js:179:24)
(node:2) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    at emitDeprecationWarning (internal/process/promises.js:161:11)
    at processPromiseRejections (internal/process/promises.js:213:13)
    at processTicksAndRejections (internal/process/task_queues.js:98:32)
```

apart from promise rejections this says that it "Cannot allocate memory".

What am I doing wrong?

**Comment by eyberg** [comment]
w/out diving into the source i'm unsure, would probably need to drill down what is causing that 

have you tried bumping the memory up just to see if that msg goes away?
 https://nanovms.gitbook.io/ops/configuration#runconfig.memory

the other thing you can do is turn on '-d' and see if there are any calls that might be triggering that error msg, also is this being ran in or out of a container?

**Comment by Dmitry-N-Medvedev** [comment]
@eyberg,

1. I have tried to set memory to both the default value and the 6G before reporting this issue
2. will do the **-d** today and report back

**Comment by eyberg** [comment]
it would also be helpful if possible to drill down to minimal reproduce-able code - seems like it's failing on the connect w/that message

```
    try {
      this.connecting = true;
      this.redis.connect(this.opts.host, this.opts.port, this.onConnect, this.onDisconnect);
    } catch(e) {
      this.emit('error', new Error(e));
```

but not sure why that would throw that error msg - I was able to run the example here https://www.npmjs.com/package/redis-fast-driver when looking at this earlier
