### ISSUE TITLE
Java package doesn't resolve names

### ISSUE THREAD

**Issue by Littlelies** [nanovms/ops#590]
When I try to adapt HelloWorld.java like this:
```
import java.net.InetAddress;

public class HelloWorld {
   public static void main(String[] args) throws Exception {
        System.out.println("Hello World!");
        System.out.println(InetAddress.getByName("api.ipify.org"));        
   }
}
```
I get
```
Exception in thread "main" java.net.UnknownHostException: api.ipify.org: System error
	at java.base/java.net.Inet4AddressImpl.lookupAllHostAddr(Native Method)
	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(InetAddress.java:924)
```
When I run the class inside docker, I have no problem. `Native Method` suggests Java Runtime is calling a kernel/glibc method to resolve host. Maybe a missing libnss3.so or similar in the package filesystem?

**Comment by Littlelies** [comment]
Error happens on both Java packages.

**Comment by eyberg** [comment]
@Littlelies seems like java 11 is latest LTS - maybe we should just create a new pkg for that?

**Comment by Littlelies** [comment]
OpenJDK 11 would be better indeed for the latest security patches.

**Comment by eyberg** [comment]
@Littlelies re-built java 11 

```
➜  j cat config.json
{
  "Files": ["HelloWorld.class", "HelloWorld.java"],
  "Args": ["HelloWorld"]
}
➜  j ops load java_11.0.8 -c config.json
```

```
➜  j cat HelloWorld.java
import java.net.InetAddress;
import java.net.UnknownHostException;

public class HelloWorld
{
    public static void main(String args[])
    {
      System.out.println("Hello, World");
      try {
        System.out.println(InetAddress.getByName("api.ipify.org"));
      }  catch (UnknownHostException e) {
         System.err.println(e);
      }
    }
}
```

lmk if that works for you?

**Comment by Littlelies** [comment]
It doesn't work when I try to request HTTPS.
There is a lot of symlinks towards /etc/java-11-openjdk that is missing.
As a temporary workaround, I had to override some symlinked files (java.policy, unlimited directory contents, cacerts), and then it works using a fixed truststore:
```
{
    "Files":["HelloWorld.class"],
    "Dirs":["usr", "lib"],
    "Args":["-Djavax.net.ssl.trustStore=/lib/security/cacerts","HelloWorld"]
}
```
You can reproduce using the following:
```
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;
import java.net.http.HttpResponse.BodyHandlers;
import java.net.URI;

public class HelloWorld {
  public static void get(String uri) throws Exception {
    HttpClient client = HttpClient.newHttpClient();
    HttpRequest request = HttpRequest.newBuilder()
          .uri(URI.create(uri))
          .build();
  
    HttpResponse<String> response =
          client.send(request, BodyHandlers.ofString());
  
    System.out.println(response.body());
  }

  public static void main(String[] args) throws Exception {
    get("https://api.ipify.org");
  }
}
```

**Comment by eyberg** [comment]
i re-pkg'd it and it works but is slow as hell, not sure if there is more config to be done or there is a deeper issue that needs to be resolved but i opened https://github.com/nanovms/nanos/issues/1259 to track it

**Comment by eyberg** [comment]
@Littlelies i'm going to close this issue but please track the one on nanos - someone is looking at it currently
