### ISSUE TITLE
panic: runtime error: index out of range [-1]

### ISSUE THREAD

**Issue by am11** [nanovms/ops#966]
Since https://github.com/nanovms/ops/commit/50a178d73871113ae0950f94e5d3ccc977fc22a8, I am getting:

```sh
# with any config.json, e.g.
$ cat ./config.json
{
  "Dirs" : ["./"]
}

$ ops run ./myApp -c ./config.json
panic: runtime error: index out of range [-1]

goroutine 1 [running]:
github.com/nanovms/ops/fs.(*Manifest).AddFileTo(0xc000456b10, 0xc000456ae0, 0xc0000344b8, 0x1, 0x0, 0x0, 0xc0002744e0, 0x1)
        /home/am11/ops/fs/manifest.go:327 +0x7a0
github.com/nanovms/ops/fs.(*Manifest).AddFile(...)
        /home/am11/ops/fs/manifest.go:312
github.com/nanovms/ops/fs.(*Manifest).AddUserProgram(0xc000456b10, 0x0, 0x0)
        /home/am11/ops/fs/manifest.go:58 +0x1c3
github.com/nanovms/ops/lepton.BuildManifest(0xc0006c1650, 0x1acaa6f, 0xc00024a300, 0xc000210700)
        /home/am11/ops/lepton/image.go:309 +0x250
github.com/nanovms/ops/lepton.BuildImage(0x3b32ba8, 0x0, 0x0, 0x0, 0x0, 0xc0000c6ba0, 0x1f, 0x0, 0x0, 0x0, ...)
        /home/am11/ops/lepton/image.go:29 +0x2f
github.com/nanovms/ops/cmd.runCommandHandler(0xc00002a780, 0xc0004564b0, 0x1, 0x3)
        /home/am11/ops/cmd/cmd_run.go:64 +0x499
github.com/spf13/cobra.(*Command).execute(0xc00002a780, 0xc0004563f0, 0x3, 0x3, 0xc00002a780, 0xc0004563f0)
        /home/am11/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:830 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0xc000248a00, 0x0, 0x96380, 0xc0000a4058)
        /home/am11/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:914 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
        /home/am11/go/pkg/mod/github.com/spf13/cobra@v0.0.5/command.go:864
main.main()
        /home/am11/ops/ops.go:8 +0x27
```

it works fine until previous commit 285a23e8b2c093baec59cd3ac7f2ecb7aa6b3d9e.

**Comment by am11** [comment]
looks like to prevent such regressions, we are missing some basic tests that exercise command-line scenarios; of the form: `exec.Command("ops", "run",...)`

**Comment by fabioDMFerreira** [comment]
Thanks for opening this issue @am11.

Increasing code covered by unit tests would definitely prevent regressions like this.

**Comment by fabioDMFerreira** [comment]
We need to add some safeguard here https://github.com/nanovms/ops/blob/master/fs/manifest.go#L327.

**Comment by am11** [comment]
With working commit, `fmt.Printf("%v\n", parts)` on line above (326) produces:

```
[lib x86_64-linux-gnu libnss_dns.so.2]
[etc ssl certs ca-certificates.crt]
[myApp]
[kernel]
[etc resolv.conf]
[proc sys kernel hostname]
[etc passwd]
[config.json]
[main.c]
[myApp]
[libc.so.6]
[ld-linux-x86-64.so.2]
```
with master, it is:

```
[lib x86_64-linux-gnu libnss_dns.so.2]
[etc ssl certs ca-certificates.crt]
[]
panic: runtime error: index out of range [-1]
```

**Comment by am11** [comment]
It is broken with any config file, even as simple as:

```json
{
  "Force": true
}
```

**Comment by fabioDMFerreira** [comment]
should be fixed in https://github.com/nanovms/ops/pull/968

**Comment by am11** [comment]
Thanks for a quick fix @fabioDMFerreira! 🚀
