### ISSUE TITLE
Ops fails on vagrant/virtualbox

### ISSUE THREAD

**Issue by cbarraford** [nanovms/ops#98]
Trying to setup Ops on vagrant/virtual box and get the follow error when trying to setup networking...

```
vagrant@ubuntu-xenial:~/go/src/github.com/nanovms/ops$ sudo ./ops net setup
panic: no DHCP packet received within 10s

goroutine 1 [running]:
main.netCommandHandler(0xc0000c6a00, 0xc00002adf0, 0x1, 0x1)
	/home/vagrant/go/src/github.com/nanovms/ops/ops.go:158 +0x136
github.com/spf13/cobra.(*Command).execute(0xc0000c6a00, 0xc00002add0, 0x1, 0x1, 0xc0000c6a00, 0xc00002add0)
	/home/vagrant/go/src/github.com/spf13/cobra/command.go:766 +0x2cc
github.com/spf13/cobra.(*Command).ExecuteC(0xc0000c7180, 0x4, 0x0, 0xc0000c6f00)
	/home/vagrant/go/src/github.com/spf13/cobra/command.go:852 +0x2fd
github.com/spf13/cobra.(*Command).Execute(0xc0000c7180, 0xc0000aff40, 0x1)
	/home/vagrant/go/src/github.com/spf13/cobra/command.go:800 +0x2b
main.main()
	/home/vagrant/go/src/github.com/nanovms/ops/ops.go:213 +0x7a9
```

**Comment by eyberg** [comment]
closing as not really a use-case we'd support - we'd support building a vbox image but not nesting one - at least not anytime in the near future
